# YOLO 國防射擊系統配置檔
# 修改此檔案後重新執行程式即可套用新設定

# 相機設定
camera:
  cam_id: 1  #若只有一個鏡頭設0

# 格式: [色相H, 飽和度S, 明度V]
# H 範圍: 0-180, S 範圍: 0-255, V 範圍: 0-255
hsv_color:
  # 紅色範圍 1 (淺紅/橘色)
  lower_red1: [0, 25, 100]
  upper_red1: [10, 255, 255]
  
  # 紅色範圍 2 (深紅色)
  # 因為紅色在 HSV 色相環的兩端,需要兩個範圍
  lower_red2: [170, 25, 100]
  upper_red2: [180, 255, 255]

